name: Build and Deploy Chatbot

on:
  push:
    branches:
      - master

jobs:
  build:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-backend:latest

      - name: Build and Push Frontend Docker Image
        env:
          VITE_APP_API_URL: ${{ vars.VITE_APP_API_URL }}
          VITE_APP_WS_URL: ${{ vars.VITE_APP_WS_URL }}
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-frontend:latest

  deploy:
    needs: build
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y ssh

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST << 'EOF'
            cd /root/mental-health-chatbot-poc
            docker compose pull
            docker compose up -d --remove-orphans
            docker compose exec backend yarn prisma migrate deploy
            exit
          EOF
